[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "jumpmodels"
version = "0.2.0"
authors = [
  { name="Yizhan Shu", email="olivershu98@gmail.com" },
  { name="Linn Bogren" },
]
description = "Statistical Jump Models in Python, with scikit-learn-style APIs. Includes Sparse Poisson Jump Model framework for count data with state-dependent rates. Original jump model framework: Yizhan Shu, olivershu98@gmail.com"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
  "numpy",
  "pandas",
  "scipy",
  "scikit-learn",
  "matplotlib",
  "tqdm (>=4.67.1,<5.0.0)",
  "seaborn (>=0.13.2,<0.14.0)",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Developers",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Information Analysis",
]
keywords = ["regime", "regime switching", "jump models", "clustering", "time series", "financial data", "poisson", "count data"]



[project.optional-dependencies]
example = [
    "jupyterlab",
    "yfinance",
]



[project.urls]
Homepage = "
Homepage_original = "https://github.com/Yizhan-Oliver-Shu/jump-models"
Issues = "https://github.com/Yizhan-Oliver-Shu/jump-models/issues"